scripts/bootstrap.sh
- use macOS standard secure tmp folder instead of `/tmp`
- use `@admin` group instead of username directly in `/etc/nix/nix.conf`
=> minor improvement to bootstrap script

plugins/dynamodb_local/process-compose.yaml
Option is documented here:
https://f1bonacc1.github.io/process-compose/launcher/#specify-a-working-directory
I have not tested the change with this plugin but I have tested the option in another projects process-compose.yaml
=> Use working_dir instead of cd in dynamodb_local process-compose

flake.lock, flake.nix, packages/adr-tools.nix
Including in this PR:
- adr-tools Nix package
- change Nixpkgs from `nixos-23.05` to `nixos-unstable`
- allow unfree Nixpkgs packages 
Reference:
- https://cultureamp.atlassian.net/browse/FEF-881
- [adr-tools: init at 3.0.0 by milibopp · Pull Request #57901 · NixOS/nixpkgs](https://github.com/NixOS/nixpkgs/pull/57901) 
- [adr-tools](https://github.com/npryce/adr-tools)
=> adr-tools package

scripts/bootstrap.sh
`$` was missing so `NIX_FINAL_SSL_FILE` ends up being `NETSKOPE_DATA_DIR/nscacert_combined.pem` which is invalid
=> Fix bootstrap.sh script when running on local machine

plugins/corepack/README.md, plugins/corepack/plugin.json
Adds a corepack plugin that enables [Corepack](https://nodejs.org/api/corepack.html) to handle PNPM and Yarn version installs while using the same version of Node.js as the project.
(largely copy-pasted from @jay-aye-see-kay's explanation on Slack)
There’s a subtle but messy issue that can arise using Devbox, Node.js, and Yarn/PNPM. If you install node and yarn as documented you will end up with two different versions of node:
```sh
$ devbox add nodejs@20.8 yarn
...
$ devbox run node --version
v20.8.0
$ devbox run yarn node --version
yarn node v1.22.19
v18.18.0
```
This happens because nix bundles all dependencies into every package, yarn is getting it’s own copy of Node.js, which may be more recent than the Node.js version the project is using.
Corepack by default tries to install shim …
=> Add corepack plugin

plugins/corepack/README.md, plugins/corepack/plugin.json
- I noticed when using this plugin repos it would use the directory `.devbox/virtenv/cultureamp-devbox-extras/bin` i.e plugins are only namespaced by repo name, and we have multiple plugins in this repo, so at the moment they'll all share the same `{{ .Virtenv }}` directory
- For now the fix is to rename the directory we use to something more unique, we should probably open this as an issue upstream too
- also update docs so they don't reference a "pnpm plugin", I think this was a typo
=> update corepack dir to be unique even if shared with other plugins

README.md, flake.lock, flake.nix, packages/mongodb-4_4.nix, packages/mongodb-6_0.nix
Add mongo 6 0 package.
This is so we can install mongo by downloading a binary rather than compiling (which is what happens if you use the nixpkgs package) to save about 20mins.
`bin/mongo` is no longer included so it has been removed.
https://www.mongodb.com/docs/v4.4/mongo/#std-label-compare-mongosh-mongo
Verified that package works in this commit https://github.com/cultureamp/murmur/pull/23612/commits/81fa6285999220952a48ef2ff0ebb3a2aa11c0ea
=> Add mongo 6 0 package

.github/workflows/ci.yaml
Noticed issue in https://github.com/cultureamp/local-ops/pull/27, which will affect this repo too
Searching the company github these are the only two repos that use this action https://github.com/search?q=org%3Acultureamp+jetpack-io%2Fdevbox-install-action&type=code
=> update devbox action to new version and org name

plugins/corepack/README.md, plugins/corepack/plugin.json
Plugin was upstreamed a few weeks ago, no need to install it explicitly - though there's currently no harm either, it can be confusing.
Puts a warning in the init_hook and readme so it's more clear. Will also make sure our internal docs are up to date.
=> deprecate corepack plugin

flake.nix, packages/multi-gitter.nix
Multi gitter is the tool chosen by SRE to do batch updates in the fleet-upgrades repo.
I have been playing around with it as well but had to install it via brew due to it not being in the nix package registry.
If we want to do more experiments with it I would like to be able to install it with devbox.
This PR adds a flake for multi-gitter
=> Add multi gitter flake

packages/multi-gitter.nix
That last PR fails install with the following message
`> cp: cannot stat 'bin/multi-gitter': No such file or directory`
This PR fixes that and has been tested locally, I just missed that error message before
=> Location of binary was in the root not in bin/multi-gitter

plugins/pipx/plugin.json
adds plugin to install [pipx](https://pipx.pypa.io) which can be used to bootstrap other system level python tools, such as Poetry
=> add pipx plugin

scripts/install_hotel.sh
This issue has come up a couple times, it's confusing at best, looks broken, so time to fix it.
Previously curl had `--fail` so it would fail on non-200 responses but the script would exit before we could do anything helpful (because `set -e`). So now we're splitting the output of curl to get both the http code and response body, this allows us to print a better error message
Uninstalled `hotel`, then tried reinstalling with a bad token, then with a good token. Works as expected, as can be seen below.
=> improve hotel installer error message

plugins/ca-kafka-local/README.md, plugins/ca-kafka-local/bin/kafka-local-readme, plugins/ca-kafka-local/config/process-compose.yaml, plugins/ca-kafka-local/plugin.json
Add a `ca-kafka-local` plugin.
This ties into our (private) https://github.com/cultureamp/local-kafka repo. It does not start the service, but it provides environment variables your project can use to connect to the service, a README with links, and the ability to set one of your services as `depends_on: kafka_local`.
Jira card: https://cultureamp.atlassian.net/browse/FEF-1537
I've tested on this branch of develop-module:
https://github.com/cultureamp/develop-module/compare/jasono/test-kafka-devbox-plugin?expand=1
=> Add a ca-kafka-local plugin

plugins/ca-kafka-local/README.md, plugins/ca-kafka-local/bin/kaf, plugins/ca-kafka-local/bin/kafka-local-readme, plugins/ca-kafka-local/config/kaf/config, plugins/ca-kafka-local/config/kafkactl/config.yaml, plugins/ca-kafka-local/config/kcat/kcat.conf, plugins/ca-kafka-local/plugin.json
This will make it easier for us to add topics, among other things.
The tools installed are:
- [kafkactl](https://deviceinsight.github.io/kafkactl/)
- [kcat](https://github.com/edenhill/kcat)
- [kaf](https://github.com/birdayz/kaf)
All 3 tools are small binaries and don't add much weight to the plugin. Kaf and Kcat are already in use elsewhere at Culture Amp, but kafkactl appeared to me to have the nicest combination of UI + docs, so I think is worth including.
I've used `envsubst` to create templated config files for each, and needed a small wrapper script to set the `--config` flag for kaf (for both kcat and kafkactl I was able to set the config path with an environment variable so didn't need a wrapper script).
Example to create a topic:
kafkactl create topic local.jasontopic.v1
Jira …
=> Start installing various Kafka CLI tools in ca-kafka-local plugin

plugins/ca-kafka-local/README.md, plugins/ca-kafka-local/bin/kafka-local-readme, plugins/ca-kafka-local/bin/kafka-local-register-schema, plugins/ca-kafka-local/plugin.json
Give teams an easy way to register an Avro schema with Schema Registry.
This is meant to be a small developer experience improvement for teams that need it, with the long term goal being to add schemas from kafka-ops resources.
Jira: https://cultureamp.atlassian.net/browse/FEF-1557
- Adds a basic shell script to register a schema with a curl command to schema registry
- Add docs for this script
- Update hotel commands to use the `up kafka` alias rather than `up kafka-local` (see https://github.com/cultureamp/hotel/pull/80)
=> Add kafka-local-register-schema script

packages/debezium-server.nix
We are missing JMX support from the `run_debezium` wrapper script as part of our debezium-server nix package.  This changes the wrapper script to source the required JMX script, so JMX is enabled if JMX_HOST and JMX_PORT are provided
- Source the jmx_enable.sh bash script
=> add jmx script to run_debezium wrapper script [DASE-1982]

plugins/debezium-server/config/process-compose.yaml, plugins/debezium-server/plugin.json
The various `devbox services` commands were failing due to the process-compose.yaml
- Fix `working_dir`
- Update service naming convention to underscores, matching other services
- Ensure postgres-version-check binary is copied across on plugin install
=> fix postgres version check

plugins/debezium-server/config/process-compose.yaml
Sometimes, a project consuming the project may have a `postgresql` service with a dependency on another service, such as a `setup`.  This causes the `init_outbox` to immediately fail if postgres isn't ready.
Similar to the `kafka_local`, we create a `postgres_wait` service that will `tail` indefinitely, and has a 3 second readiness probe to confirm postgres is ready. Once ready, `init_outbox` can run successfully.
Add `postgres_wait` service to check postgres is ready, and have `init_outbox` depend on this, so we don't attempt to setup postgres before ready.
=> Add indefinite wait with readiness check to ensure postgres running

.github/workflows/ci.yaml, .rubocop.yml, README.md, devbox.json, devbox.lock, scripts/github_auth.rb, scripts/install_hotel.rb, scripts/install_hotel.sh
`hotel` is now using Github app authentication. This PR is intending to have the install flow for  `hotel` use this same authentication flow, and set up the tokens ready for `hotel` to consume.
The end-to-end test has been removed and replaced with a test of the install script. The authentication is unable to be tested as it requires interaction with the browser, however the functions of the install are still tested, and should authentication break we are still able to override with PAT tokens.
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/cultureamp/devbox-extras/tfm/fef-1572-gh-auth/scripts/github_auth.rb)"`
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/cultureamp/devbox-extras/main/scripts/install_hotel.sh) {insert_pat_token_here}"`
=> Github App authentication

README.md
The ruby script URL was not using the raw.githubusercontent.com url so this has been updated.
=> Fix script url

plugins/debezium-server/bin/populate.ts, plugins/debezium-server/plugin.json
We currently provide an Avro schema file and sample data JSON that will allow users to run `devbox run populate`, resulting in Avro-encoded payloads being published to the outbox table.
However, the environment variables for these are hard-coded, and cannot be overridden
- Set relevant environment variables as export in `init_hook`, so users can override and register their own schema plus publish their own data
- Print out the schema file path when registering against schema registry
=> Allow custom schema and data file paths, print file path on registering

scripts/install_hotel.sh
install_hotel.sh calls a `hotel` command which requires Github authentication. In CI we cannot use the Github app authentication as it is a non-interactive environment. To get around this we use a token, however previously this token was not provided to `hotel`. As `hotel` now requires this token we should configure it to use it.
=> If install_hotel.sh is run with token, configure hotel to use this token

scripts/install_hotel.sh
In order to make CI able to install hotel we write a token to a config file. However the behaviour I wrote for this was always writing to a config file whether being installed in CI or on a developer's machine.
A new variable has been introduced to check if we are using a PAT, and if so the install script will write to file. Previously we were checking if a variable containing the token existed, however this variable always existed.
https://github.com/cultureamp/devbox-extras/pull/51
=> only write to config when using PAT

plugins/debezium-server/bin/populate.ts, plugins/debezium-server/plugin.json
There are a couple of fixes / changes to apply for the Debezium Server DevBox plugin surrounding environment variable usage
- The database host should be `DB_HOSTNAME` in the populate script, not `DB_HOST`
- We default the `DB_PORT` to `PGPORT` where it exists with `5432` (the postgres default) as a fallback.  Some teams were overriding `PGPORT` and were not also updating `DB_PORT` at the same time, which was confusing
=> Database environment variable fixes for Debezium Server

plugins/ca-kafka-local/bin/kafka-local-register-schema
Updates the `kafka-local-register-schema` script to add the `-value` suffix to the schema name. This is to ensure that message values can be serialised using avro when publishing data to a particular topic.
Before change:
After change:
=> Add '-value' suffix to schema name in schema registration script.

plugins/ca-changesets/README.md, plugins/ca-changesets/bin/ca-changeset-wrapper, plugins/ca-changesets/plugin.json
A thin wrapper to @changesets/cli, using the `npx` command to call `changeset`. 
This will install `changeset` if it does not already exist, without requirement of a `package.json` file, and without creating a `node_modules/` directory.
I have ensured that:
- This plugin will install nodejs, however the consuming devbox project's node version will not be clobbered, as the project's environment is loaded after the plugin environment.
=> introduces ca-changesets plugin

plugins/debezium-server/config/process-compose.yaml, plugins/debezium-server/plugin.json
This PR changes the readiness command to allow the Debezium server plugin to use a postgres outside of the devbox virtual environment.
=> feat: allow external postgres to be used by debezium plugin

scripts/install_hotel.sh
Recently we had an issue in the install script where no downloaded Github release filename matched the hotel release we expected. There was no error messaging to declare this problem. To fix this I have introduced a print statement for this case which links out to documentation on how to manually install `hotel`.
Context: https://cultureamp.slack.com/archives/C05D8BD1CB1/p1738902067155539
=> Install script prints error when latest release not found

packages/debezium-server.nix, plugins/debezium-server/config/debezium-server/application.properties, plugins/debezium-server/config/debezium-server/init_outbox.sql, plugins/debezium-server/plugin.json
The current stable version of Debezium Server listed [here](https://debezium.io/releases/) is `3.0`, and we are currently on `2.7`.
This includes an update to the Nix flake and required configuration changes so Debezium server `3.0.0.Final` can be used locally
=> Bump debezium to 3.0.0.Final

devbox.lock, process-compose/README.md, process-compose/schema.yaml
To avoid errors, and provide autocompletion functionality I have produced a schema for `process-compose.yaml` files. This PR includes this schema, as well as some documentation on how to make use of the schema.
This PR also bumps the devbox lockfile to include the changes introduced in devbox v0.14.0.
You can use this schema prior to it being merged to main by using the url "https://raw.githubusercontent.com/cultureamp/devbox-extras/tfm/process-compose-schema/process-compose/schema.yaml" like the below.
```yaml
```
=> adds process-compose schema

plugins/ca-kafka-local/config/kafkactl/config.yaml, plugins/ca-kafka-local/plugin.json
kafkactl config.yaml is incorrectly structured, and will not Avro encode with schema registry.
This fixes up the expected file structure so `kafkactl` can successfully produce Avro encoded messages to local Kafka
=> fix schema registry in kafkactl config

plugins/ca-kafka-local/plugin.json
The kafka local plugin includes `kafkactl@5`, however different repositories using this plugin are installing different versions -- and the versioning does not seem to respect semantic versioning.
For example, from v5.5.1 to v5.6.0: https://github.com/deviceinsight/kafkactl/releases/tag/v5.6.0
A PR is introduced [here](https://github.com/deviceinsight/kafkactl/pull/240) that changes the configuration file structure, which is a breaking change.
We should lock kafkactl to a specific version to avoid any unexpected breaking changes
=> lock kafkactl version due to breaking changes

packages/multi-gitter.nix
adds `stripRoot=false` as suggested by build failure
=> fix multi-gitter package that wasn't building on newer nix versions

packages/multi-gitter.nix
went down a bit of a rabbit hole getting the hashes the proper way
- previously I'd been using and recommending the "fake hash method", but found that to be clumsy for multiple cpu archs and have run into obscure netskope issues
- see: https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-fetchers-updating-source-hashes-fakehash-method
- figuring out the correct chaining of `nix-hash` and `nix-prefetch-*` was something I've been trying to do for a while, this seems pretty solid
=> update multi-gitter to latest

plugins/ca-ruler/README.md, plugins/ca-ruler/bin/ca-ruler-wrapper, plugins/ca-ruler/plugin.json
A few projects are now making use of the npm package `@intellectronica/ruler`, this plugin is intended to make it easier to use for projects that don't depend on node.
We've chosen to roll this out as a devbox plugin as it will allow us to change the implementation. Potential reasons for changing the implementation include: 
- Managing hooks
- Delivering enterprise wide policies for all agents, although we could achieve this with `hotel`.
Being a devbox plugin also grants us the ability to write files (such as initialising ruler config, or extending rule files) as well as run scripts (such as managing the ruler initialisation). 
To verify the work in this PR you can add the following to the `devbox.json` of some project in the same folder as devbox-extras.
```
"include": [ …
```
=> adds ca-ruler plugin

plugins/debezium-server/config/process-compose.yaml, plugins/debezium-server/plugin.json
This is so that is appears in a projects as `README_DEBEZIUM` instead of
`readme` which can conflict with a projects readme process.
=> Rename debezium readme process
